package com.enl.noah.config_enl.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.enl.noah.config_enl.entity.greendao.ViewConfig;

import com.enl.noah.config_enl.greendao.ViewConfigDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig viewConfigDaoConfig;

    private final ViewConfigDao viewConfigDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        viewConfigDaoConfig = daoConfigMap.get(ViewConfigDao.class).clone();
        viewConfigDaoConfig.initIdentityScope(type);

        viewConfigDao = new ViewConfigDao(viewConfigDaoConfig, this);

        registerDao(ViewConfig.class, viewConfigDao);
    }
    
    public void clear() {
        viewConfigDaoConfig.clearIdentityScope();
    }

    public ViewConfigDao getViewConfigDao() {
        return viewConfigDao;
    }

}
